name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linter (if configured)
      run: npm run lint || echo "No linter configured"
      continue-on-error: true
    
    - name: Run tests
      run: npm test
    
    - name: Run test coverage
      run: npm run test:coverage
    
    - name: Upload coverage to Codecov (optional)
      uses: codecov/codecov-action@v3
      if: matrix.node-version == '20.x'
      continue-on-error: true
      with:
        files: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Check for build script
      id: check_build
      run: |
        if grep -q "\"build\":" package.json; then
          echo "has_build=true" >> $GITHUB_OUTPUT
        else
          echo "has_build=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Build project
      if: steps.check_build.outputs.has_build == 'true'
      run: npm run build


